### PR TITLE
Various improvements from the NoRedInk/ branch

### PR DESCRIPTION
**Pull request by jwoudenberg**
As discussed previously @supermario, these are some changes we added on our fork of `elm-export`. We'd love to combine these all in one place.

- Fixes for decoder/encoder generation of `newtype` and `unit` types.
- `ElmType` instance for servant `Headers`.

### CODE REVIEW

**Comment by supermario** [comment]
Nice, thanks @jwoudenberg! I'll work through this week. I see you've also done a conversion to hpack 👍

**Comment by jwoudenberg** [comment]
The conversion of hpack comes from Kris' commits (from the devel branch).

**Comment by supermario** [comment]
Ah. 😅

**Comment by supermario** [comment]
Ok - I'm going to merge this in and then work on updating the changelog and reconciling a few things, including the removal of https://github.com/supermario/elm-export/commit/cb1966c604f1eb02914a52be4fefa328fcbc6a92 due to issues documented in https://github.com/krisajenkins/elm-export/pull/48.

**Pull request merged**
